# -*- coding: utf-8 -*-
import numpy as np
import nibabel as nib
from os.path import join as opj


def correct_dwi_conmat(atlas, subject):
    """
    This function cleans the conmat generated by mrtrix3 pipeline
    
    Possible errors: If the ROIs are too small in the atlas, when transforming
    to DWI space, some may dissapear. This would create conmats with smaller #
    of rois than the original atlas.
    """

    conmat = opj(folder_path, subject) # TODO: folder_path

    img_data = nib.load(atlas).get_data()
    conmat_data = np.loadtxt(conmat)

    rois = np.unique(img_data)[1:]-1
    return conmat_data[np.ix_(rois, rois)]
